# Generated by Django 4.2 on 2025-03-26 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_product_price_large_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
